# Generated by Django 4.0.4 on 2022-05-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_meeting_time_meeting_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=15, verbose_name='Organization Name')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('opening', models.TextField()),
                ('members_present', models.TextField()),
                ('members_absent', models.TextField()),
                ('business_from_the_previous_meeting', models.TextField()),
                ('new_business', models.TextField()),
                ('additions_to_the_agenda', models.TextField()),
                ('adjournment', models.TextField()),
                ('minutes_submitted_by', models.CharField(max_length=15, verbose_name='Organization Name')),
                ('minutes_approved_by', models.CharField(max_length=15, verbose_name='Organization Name')),
            ],
        ),
    ]
