# Generated by Django 4.0.4 on 2022-05-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutes',
            name='opening',
        ),
        migrations.AlterField(
            model_name='minutes',
            name='additions_to_the_agenda',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='adjournment',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='business_from_the_previous_meeting',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='members_absent',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='members_present',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='minutes_approved_by',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='minutes_submitted_by',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='new_business',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='org_name',
            field=models.CharField(max_length=20, verbose_name='Organization Name'),
        ),
    ]
